
const cfg=window.COG_CONFIG;let positions=[],subs=[],built=false;const gears=document.getElementById('gears'),count=document.getElementById('count'),toolbar=document.getElementById('toolbar'),badge=document.getElementById('readyBadge');const key='extraordinary_cogs_event_start';
async function init(){positions=await(await fetch('positions.json')).json();if(!localStorage.getItem(key))localStorage.setItem(key,'1970-01-01T00:00:00.000Z');await load()}
async function load(){const cutoff=localStorage.getItem(key),c=supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);const q=await c.from('submissions').select('id,participant_name,image_path,created_at').gte('created_at',cutoff).order('created_at',{ascending:true}).limit(75);if(q.error){console.error(q.error);count.textContent='?';return}subs=[];for(const s of q.data){const u=c.storage.from('cogs').getPublicUrl(s.image_path);subs.push({...s,image_data:u.data.publicUrl})}count.textContent=subs.length}
function make(s,p){const e=document.createElement('div');e.className=`gear ${p.direction}`;e.style.left=p.x+'%';e.style.top=p.y+'%';e.style.setProperty('--size',p.size+'vw');e.style.setProperty('--duration',p.duration+'s');e.style.backgroundImage=`url("${s.image_data}")`;gears.appendChild(e);return e}
function build(){if(built)return;built=true;gears.innerHTML='';const ord=positions.slice().sort((a,b)=>a.ring-b.ring||a.id-b.id),els=subs.slice(0,75).map((s,i)=>make(s,ord[i]));els.forEach((e,i)=>setTimeout(()=>{e.classList.add('ready');setTimeout(()=>e.classList.add('spinning'),280)},i*115))}
function reset(){built=false;gears.innerHTML='';document.getElementById('reveal').classList.remove('show')}
function fresh(){if(!confirm('Start fresh now? Earlier test cogs will be hidden from this event.'))return;localStorage.setItem(key,new Date().toISOString());subs=[];count.textContent=0;reset()}
function toggle(hide){toolbar.classList.toggle('hide-ui',hide);badge.classList.toggle('hide-ui',hide)}
document.getElementById('fresh').onclick=fresh;document.getElementById('refresh').onclick=load;document.getElementById('build').onclick=build;document.getElementById('message').onclick=()=>document.getElementById('reveal').classList.add('show');document.getElementById('reset').onclick=reset;document.getElementById('hide').onclick=()=>toggle(true);document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')toggle(!toolbar.classList.contains('hide-ui'))});init();
